// Generated by jextract

package com.kjipo.potrace;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct potrace_param_s {
 *     int turdsize;
 *     int turnpolicy;
 *     double alphamax;
 *     int opticurve;
 *     double opttolerance;
 *     potrace_progress_t progress;
 * } potrace_param_t
 * }
 */
public class potrace_param_t extends potrace_param_s {

    potrace_param_t() {
        // Should not be called directly
    }
}

