// Generated by jextract

package com.kjipo.potrace;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct potrace_state_s {
 *     int status;
 *     potrace_path_t *plist;
 *     struct potrace_privstate_s *priv;
 * } potrace_state_t
 * }
 */
public class potrace_state_t extends potrace_state_s {

    potrace_state_t() {
        // Should not be called directly
    }
}

