// Generated by jextract

package com.kjipo.potrace;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct potrace_bitmap_s {
 *     int w;
 *     int h;
 *     int dy;
 *     potrace_word *map;
 * } potrace_bitmap_t
 * }
 */
public class potrace_bitmap_t extends potrace_bitmap_s {

    potrace_bitmap_t() {
        // Should not be called directly
    }
}

