// Generated by jextract

package com.kjipo.potrace;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct potrace_curve_s {
 *     int n;
 *     int *tag;
 *     potrace_dpoint_t (*c)[3];
 * } potrace_curve_t
 * }
 */
public class potrace_curve_t extends potrace_curve_s {

    potrace_curve_t() {
        // Should not be called directly
    }
}

