// Generated by jextract

package com.kjipo.potrace;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct potrace_path_s {
 *     int area;
 *     int sign;
 *     potrace_curve_t curve;
 *     struct potrace_path_s *next;
 *     struct potrace_path_s *childlist;
 *     struct potrace_path_s *sibling;
 *     struct potrace_privpath_s *priv;
 * } potrace_path_t
 * }
 */
public class potrace_path_t extends potrace_path_s {

    potrace_path_t() {
        // Should not be called directly
    }
}

