// Generated by jextract

package com.kjipo.potrace;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct potrace_progress_s {
 *     void (*callback)(double, void *);
 *     void *data;
 *     double min;
 *     double max;
 *     double epsilon;
 * } potrace_progress_t
 * }
 */
public class potrace_progress_t extends potrace_progress_s {

    potrace_progress_t() {
        // Should not be called directly
    }
}

